# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DIPREME
email: your-email@domain.com
description: Direcção Provincial de Recursos Minerais e Energia de Tete
url: ""
github:
  username: zinenda
  url: "https://zinenda.github.io/dprme"

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: assets/_sass
  style: compressed

author: Ivo zinenda
twitter:
  username: Imaz_3g

logo: 

port: 4001

origin: https://github.com/Zinenda/dprme.git