# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DPRME
email: your-email@domain.com
description: Direcção Provincial de Recursos Minerais e Energia
url: ""
github:
  username: zinenda
  url: ""

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-sitemap